{
 "title": "Throughput",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sent/Received Msg Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mq_benchmark_consumer_messages_received_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "mq_benchmark_producer_messages_sent_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mq_benchmark_consumer_throughput_msg_per_sec",
     "legendFormat": "__auto"
    },
    {
     "expr": "mq_benchmark_producer_throughput_msg_per_sec",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mq_benchmark_consumer_latency_ms_sum/mq_benchmark_consumer_latency_ms_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "mq_benchmark_producer_latency_ms_sum/mq_benchmark_producer_latency_ms_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Consumers and Producers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "mq_benchmark_active_consumers", "legendFormat": "__auto" },
    { "expr": "mq_benchmark_active_producers", "legendFormat": "__auto" }
   ]
  }
 ]
}